# Generated by Django 5.0.6 on 2025-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enum',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('veterinario', 'Veterinario'), ('sucursal', 'Sucursal')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
