# Generated by Django 5.0.6 on 2025-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_enum_user_role_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
