# Generated by Django 5.0.6 on 2025-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='slug',
        ),
        migrations.AddField(
            model_name='animaltype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
