# Generated by Django 5.0.6 on 2025-08-23 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pettransfer',
            name='pets_pettra_code_868e7a_idx',
        ),
        migrations.AddField(
            model_name='pet',
            name='last_transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettransfer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettransfer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pettransfer',
            name='code',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='pettransfer',
            index=models.Index(fields=['pet', 'status'], name='pets_pettra_pet_id_fb4dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='pettransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('pet',), name='uniq_pending_transfer_per_pet'),
        ),
    ]
