# Generated by Django 5.0.6 on 2025-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_animaltype_slug_animaltype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='description',
        ),
        migrations.AddField(
            model_name='animaltype',
            name='slug',
            field=models.SlugField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pets/photos/'),
        ),
    ]
