# Generated by Django 5.0.6 on 2025-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_pettransfer_pets_pettra_code_868e7a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaltype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pettransfer',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
