# Generated by Django 5.0.6 on 2025-09-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_animaltype_description_animaltype_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='animal_type',
        ),
    ]
