# Generated by Django 5.0.6 on 2025-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
